dtre_oeil_site:
    resource: "@DTREOeilSiteBundle/Resources/config/routing.yml"
    prefix:   /oeil

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
