dtre_oeil_site_homepage:
    path:     /
    defaults: { _controller: DTREOeilSiteBundle:Default:index }

dtre_oeil_site_api_registration:
    path:     /api-registration
    defaults: { _controller: DTREOeilSiteBundle:Default:api }

dtre_oeil_site_api_new_token:
    path:     /api-refresh-token
    defaults: { _controller: DTREOeilSiteBundle:Default:apitoken }

dtre_oeil_site_graphique:
    path:     /graphics
    defaults: { _controller: DTREOeilSiteBundle:Default:graphics }

dtre_oeil_site_video:
    path:     /video
    defaults: { _controller: DTREOeilSiteBundle:Default:video }

dtre_oeil_site_media:
    path:     /media
    defaults: { _controller: DTREOeilSiteBundle:Default:media }

dtre_oeil_site_users:
    path:     /users
    defaults: { _controller: DTREOeilSiteBundle:Admin:users }

dtre_oeil_site_delete_user:
    path:     /user/{id}/delete
    defaults:
        _controller: DTREOeilSiteBundle:Admin:deleteuser
    requirements:
            id:   \d+
